### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bugb**
Update README file for more readable!

### CODE REVIEW

**Comment by bugb** [comment]
@bcoe  thank you for your nice work, I want to modify your README.md file a little bit, because my company use your package but the first time they look the README.md file they only think that a certain number of words can be hide. After that I look closely to your source code and I found that your package support the words to be hide on demand, I think the README.md file is out of date a bit and it should be updated so anyone new can easy take the opportunity of using it.
Any chance to merge it?

**Comment by bcoe** [comment]
@bugb I will happily land this, mind just changing the sentence:

`And it should work :)`

to:

`Any keys within obj that are contained within thebadWords array will be hidden.`

**Comment by bugb** [comment]
@bcoe hi my friend, I just update the `README.md` file as you wish, could you please take a look on it?

**Comment by bcoe** [comment]
@bugb thanks for the contribution, I've released a new version of the module to npm.

**Pull request merged**
